set-option -sa terminal-overrides ",xterm*:Tc"
set -g xterm-keys on
set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n M-h previous-window
bind -n M-l next-window

bind -n M-Left  resize-pane -L 5
bind -n M-Right resize-pane -R 5
bind -n M-Up    resize-pane -U 2
bind -n M-Down  resize-pane -D 2

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection 
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle 
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind x kill-pane

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @tmux-gruvbox 'dark'

run '~/.tmux/plugins/tpm/tpm'
